name: youtube_transcript_dart
description: A package to fetch YouTube video transcripts.
version: 1.0.0
repository: https://github.com/gabebro123/transcriptify

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.3
  html: ^0.15.5
  web: ^1.1.1 
  js: ^0.7.2  

dev_dependencies:
  test: ^1.16.0
