name: youtube_transcript_dart
description: " Transcriptify is a Dart package that allows you to easily fetch and parse YouTube video transcripts.
  It provides support for multiple languages, automatic and manually created subtitles, 
  and can be integrated into Dart or Flutter applications. This package simplifies extracting 
  captions from YouTube videos without requiring API keys, making it a lightweight and 
  developer-friendly solution."
version: 0.1.0
repository: https://github.com/gabebro123/transcriptify

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
    http: ^1.3.0
    html: ^0.15.5
    js: ^0.7.1

dev_dependencies:
  test: ^1.16.0
  lints: ^5.1.1
  flutter_lints: ^5.0.0
  flutter:
    sdk: flutter
  mockito: ^5.4.5
  build_runner: ^2.1.7