name: youtube_transcript_dart
description: "A Dart package for fetching YouTube video transcripts."
version: 0.1.0
repository: https://github.com/yourusername/youtube_transcript_dart

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  http: ^1.3.0
  html: ^0.15.5
  js: ^0.7.1

dev_dependencies:
  test: ^1.20.0
